"""stamp after manual sql

Revision ID: c9d48c40c9b9
Revises: 25a757b7c9a9
Create Date: 2026-03-16 19:09:50.114069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d48c40c9b9'
down_revision = '25a757b7c9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('diet_plan', schema=None) as batch_op:
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('food_name')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('health_checkup', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('health_checkup_pet_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pet', ['pet_id'], ['id'])

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pet_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.alter_column('vaccine_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.alter_column('vaccine_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pet_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('health_checkup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('health_checkup_pet_id_fkey'), 'pets', ['pet_id'], ['id'])

    with op.batch_alter_table('diet_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('food_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
